# Site settings
title: Learn Chinese
email: 
description: "Chinese translated into English"
baseurl: ""
url: "http://learn-chinese.github.io"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
